const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');
const fs = require('fs');

// Load configurations
const googleConfig = JSON.parse(fs.readFileSync('google-service-account-config.json', 'utf8'));

class ContinuousUpdater {
    constructor() {
        this.doc = null;
        this.serviceAccountAuth = new JWT({
            email: googleConfig.client_email,
            key: googleConfig.private_key,
            scopes: [
                'https://www.googleapis.com/auth/spreadsheets',
                'https://www.googleapis.com/auth/drive.file',
            ],
        });
        this.lastUpdateCount = 0;
    }

    async initialize() {
        console.log('🔧 Initializing Continuous Updater...');
        
        this.doc = new GoogleSpreadsheet('1nzknj5DlU_1oXeu_7VcMRD6_FRcSkgef2I0ObXxYoLg', this.serviceAccountAuth);
        await this.doc.loadInfo();
        console.log(`📊 Connected to: ${this.doc.title}`);
    }

    async updateSheets() {
        if (!fs.existsSync('batch-analysis-results.json')) {
            console.log('❌ No results file found yet');
            return 0;
        }

        const results = JSON.parse(fs.readFileSync('batch-analysis-results.json', 'utf8'));
        
        if (results.length <= this.lastUpdateCount) {
            console.log(`📊 No new results to update (${results.length} total, ${this.lastUpdateCount} already updated)`);
            return 0;
        }

        const newResults = results.slice(this.lastUpdateCount);
        console.log(`📤 Updating sheets with ${newResults.length} new results...`);

        // Update Complete Real Analysis sheet
        const analysisSheet = this.doc.sheetsByTitle['Complete Real Analysis'];
        const newRows = newResults.map(result => ({
            'Business Name': result.businessName || '',
            'Phone Number': result.phoneNumber || 'Not provided',
            'Location': result.location || '',
            'Industry': result.industry || '',
            'Website URL': result.website || 'No website',
            'Has Website': result.websiteAnalysis?.hasWebsite ? 'YES' : 'NO',
            'Business Type': result.websiteAnalysis?.businessType || 'Unknown',
            'Website Issues': result.websiteAnalysis?.issues?.join(', ') || 'None found',
            'Website Opportunities': result.websiteAnalysis?.opportunities?.join(', ') || 'None identified',
            'Google Maps Listed': result.mapsAnalysis?.isListed ? 'YES' : 'NO',
            'Google Maps Rating': result.mapsAnalysis?.rating || 'N/A',
            'Google Maps Reviews': result.mapsAnalysis?.reviewCount || 0,
            'Google Maps Issues': result.mapsAnalysis?.issues?.join(', ') || 'None found',
            'Google Maps Strengths': result.mapsAnalysis?.strengths?.join(', ') || 'None identified',
            'Total Issues Found': (result.websiteAnalysis?.issues?.length || 0) + (result.mapsAnalysis?.issues?.length || 0),
            'AI Personalized Message': result.personalizedMessage || '',
            'Analysis Date': result.timestamp || new Date().toISOString(),
            'Generated By': 'ChatGPT-4',
            'Status': 'Ready for Outreach',
            'Notes': `Teléfono: ${result.phoneNumber || 'No proporcionado'} | Ubicación: ${result.location} | Industria: ${result.industry}`
        }));

        await analysisSheet.addRows(newRows);
        console.log(`✅ Added ${newRows.length} rows to Complete Real Analysis sheet`);

        // Update Copy Paste Messages sheet
        const messagesSheet = this.doc.sheetsByTitle['Copy Paste Messages'];
        const messageRows = newResults.map(result => ({
            'Business Name': result.businessName || '',
            'Phone Number': result.phoneNumber || '',
            'Message to Send': result.personalizedMessage || '',
            'Business Type': result.websiteAnalysis?.businessType || result.industry || 'Unknown',
            'Location': result.location || ''
        }));

        await messagesSheet.addRows(messageRows);
        console.log(`✅ Added ${messageRows.length} rows to Copy Paste Messages sheet`);

        this.lastUpdateCount = results.length;
        console.log(`📊 Total leads in sheets: ${this.lastUpdateCount}`);
        
        return newResults.length;
    }

    async runContinuousUpdate() {
        console.log('🔄 Starting continuous updates...');
        
        while (true) {
            try {
                const updated = await this.updateSheets();
                if (updated > 0) {
                    console.log(`🎉 Updated ${updated} new leads!`);
                }
                
                // Check every 30 seconds
                await new Promise(resolve => setTimeout(resolve, 30000));
                
            } catch (error) {
                console.log(`❌ Update error: ${error.message}`);
                await new Promise(resolve => setTimeout(resolve, 10000));
            }
        }
    }
}

// Main execution
async function main() {
    const updater = new ContinuousUpdater();
    
    try {
        await updater.initialize();
        await updater.runContinuousUpdate();
        
    } catch (error) {
        console.error('❌ Error:', error);
    }
}

if (require.main === module) {
    main();
}

module.exports = ContinuousUpdater;

