const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');
const fs = require('fs');

// Load configurations
const googleConfig = JSON.parse(fs.readFileSync('google-service-account-config.json', 'utf8'));

class SimpleUploader {
    constructor() {
        this.doc = null;
        this.serviceAccountAuth = new JWT({
            email: googleConfig.client_email,
            key: googleConfig.private_key,
            scopes: [
                'https://www.googleapis.com/auth/spreadsheets',
                'https://www.googleapis.com/auth/drive.file',
            ],
        });
    }

    async initialize() {
        console.log('🔧 Initializing Simple Uploader...');
        
        this.doc = new GoogleSpreadsheet('1nzknj5DlU_1oXeu_7VcMRD6_FRcSkgef2I0ObXxYoLg', this.serviceAccountAuth);
        await this.doc.loadInfo();
        console.log(`📊 Connected to: ${this.doc.title}`);
    }

    async uploadToExistingSheet() {
        console.log('📤 Uploading to existing sheet...');
        
        // Check if results file exists
        if (!fs.existsSync('batch-analysis-results.json')) {
            console.log('❌ No batch analysis results found.');
            return;
        }

        // Load results
        const results = JSON.parse(fs.readFileSync('batch-analysis-results.json', 'utf8'));
        console.log(`📊 Found ${results.length} results to upload`);

        // Use the existing "Complete Real Analysis" sheet
        let analysisSheet;
        try {
            analysisSheet = this.doc.sheetsByTitle['Complete Real Analysis'];
            console.log('✅ Found Complete Real Analysis sheet');
        } catch (error) {
            console.log('📝 Creating Complete Real Analysis sheet...');
            analysisSheet = await this.doc.addSheet({
                title: 'Complete Real Analysis'
            });
        }

        // Clear existing data
        await analysisSheet.clear();
        
        // Add headers
        await analysisSheet.setHeaderRow([
            'Business Name',
            'Phone Number', 
            'Location',
            'Industry',
            'Website URL',
            'Has Website',
            'Business Type',
            'Website Issues',
            'Website Opportunities',
            'Google Maps Listed',
            'Google Maps Rating',
            'Google Maps Reviews',
            'Google Maps Issues',
            'Google Maps Strengths',
            'Total Issues Found',
            'AI Personalized Message',
            'Analysis Date',
            'Generated By',
            'Status',
            'Notes'
        ]);

        // Add results
        const rowsToAdd = results.map(result => ({
            'Business Name': result.businessName || '',
            'Phone Number': result.phoneNumber || 'Not provided',
            'Location': result.location || '',
            'Industry': result.industry || '',
            'Website URL': result.website || 'No website',
            'Has Website': result.websiteAnalysis?.hasWebsite ? 'YES' : 'NO',
            'Business Type': result.websiteAnalysis?.businessType || 'Unknown',
            'Website Issues': result.websiteAnalysis?.issues?.join(', ') || 'None found',
            'Website Opportunities': result.websiteAnalysis?.opportunities?.join(', ') || 'None identified',
            'Google Maps Listed': result.mapsAnalysis?.isListed ? 'YES' : 'NO',
            'Google Maps Rating': result.mapsAnalysis?.rating || 'N/A',
            'Google Maps Reviews': result.mapsAnalysis?.reviewCount || 0,
            'Google Maps Issues': result.mapsAnalysis?.issues?.join(', ') || 'None found',
            'Google Maps Strengths': result.mapsAnalysis?.strengths?.join(', ') || 'None identified',
            'Total Issues Found': (result.websiteAnalysis?.issues?.length || 0) + (result.mapsAnalysis?.issues?.length || 0),
            'AI Personalized Message': result.personalizedMessage || '',
            'Analysis Date': result.timestamp || new Date().toISOString(),
            'Generated By': 'ChatGPT-4',
            'Status': 'Ready for Outreach',
            'Notes': `Teléfono: ${result.phoneNumber || 'No proporcionado'} | Ubicación: ${result.location} | Industria: ${result.industry}`
        }));

        await analysisSheet.addRows(rowsToAdd);
        
        console.log(`🎉 Successfully uploaded ${results.length} results!`);
        console.log('📊 Check the "Complete Real Analysis" sheet in your Google Sheets');
    }
}

// Main execution
async function main() {
    const uploader = new SimpleUploader();
    
    try {
        await uploader.initialize();
        await uploader.uploadToExistingSheet();
        
    } catch (error) {
        console.error('❌ Error during upload:', error);
    }
}

if (require.main === module) {
    main();
}

module.exports = SimpleUploader;
