import React from 'react';
import {
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  spring,
  Audio,
  OffthreadVideo,
  staticFile,
  Sequence,
  AbsoluteFill,
} from 'remotion';

const GOLD = '#C5A059';
const BG = '#0f1115';
const CARD = '#1a1d24';
const WHITE = '#FFFFFF';
const MUTED = '#94a3b8';

export interface Caption {
  text: string;
  startSec: number;
  endSec: number;
}

export type AnnotationType = 'stat_burst' | 'icon_pop' | 'step_badge' | 'timer_pop' | 'warning_pop';

export interface Annotation {
  type: AnnotationType;
  startSec: number;
  endSec: number;
  // stat_burst: value = "21X"
  // icon_pop:   value = "📱", label = "WhatsApp", color = "#25D366"
  // step_badge: value = "1",  label = "Primer paso"
  // timer_pop:  value = "⏱️", label = "5 MIN"
  // warning_pop: value = "⏰ 12 HORAS", label = "Demasiado tarde"
  value: string;
  label?: string;
  color?: string;
}

export interface ShortProps {
  hookStat: string;
  hookStatLabel: string;
  hookText: string;
  hookPillar: string;
  clip1: string;
  clip2: string;
  voiceover: string;
  captions: Caption[];
  annotations?: Annotation[]; // narration-synced overlays — auto-generated by annotation_system.py
  ctaLine1?: string;
  educational?: boolean; // true = subscribe CTA, false = jegodigital.com CTA
}

// "Jego" GOLD + "Digital" WHITE — always top-right
const Logo: React.FC<{ size?: number }> = ({ size = 28 }) => (
  <div style={{
    position: 'absolute', top: 40, right: 32,
    display: 'flex', alignItems: 'baseline',
    zIndex: 200,
    filter: 'drop-shadow(0 2px 8px rgba(0,0,0,0.8))',
  }}>
    <span style={{ fontFamily: 'Arial Black, sans-serif', fontWeight: 900, fontSize: size, color: GOLD }}>Jego</span>
    <span style={{ fontFamily: 'Arial Black, sans-serif', fontWeight: 900, fontSize: size, color: WHITE }}>Digital</span>
  </div>
);

const HookCard: React.FC<Pick<ShortProps, 'hookStat' | 'hookStatLabel' | 'hookText' | 'hookPillar'>> = ({
  hookStat, hookStatLabel, hookText, hookPillar,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const logoScale = spring({ frame, fps, config: { damping: 14 } });
  const statIn = interpolate(frame, [6, 20], [0, 1], { extrapolateRight: 'clamp' });
  const statY = interpolate(frame, [6, 20], [40, 0], { extrapolateRight: 'clamp' });
  const textIn = interpolate(frame, [22, 38], [0, 1], { extrapolateRight: 'clamp' });

  return (
    <AbsoluteFill style={{
      background: BG,
      display: 'flex', flexDirection: 'column',
      alignItems: 'center', justifyContent: 'center',
      fontFamily: 'Arial Black, Arial, sans-serif',
    }}>
      {/* Top gold bar */}
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 6, background: GOLD }} />

      {/* Logo */}
      <div style={{
        position: 'absolute', top: 40, right: 32,
        display: 'flex', alignItems: 'baseline',
        transform: `scale(${logoScale})`, transformOrigin: 'top right',
      }}>
        <span style={{ fontWeight: 900, fontSize: 28, color: GOLD }}>Jego</span>
        <span style={{ fontWeight: 900, fontSize: 28, color: WHITE }}>Digital</span>
      </div>

      {/* Pillar */}
      <div style={{ fontSize: 20, fontWeight: 700, color: GOLD, letterSpacing: '3px', marginBottom: 20, opacity: statIn }}>
        {hookPillar}
      </div>

      {/* Big stat */}
      <div style={{
        fontSize: 160, fontWeight: 900, color: GOLD, lineHeight: 1,
        opacity: statIn, transform: `translateY(${statY}px)`,
        textShadow: '0 8px 40px rgba(197,160,89,0.35)',
      }}>
        {hookStat}
      </div>

      {/* Stat label */}
      <div style={{
        fontSize: 30, fontWeight: 700, color: WHITE,
        letterSpacing: '2px', opacity: statIn,
        transform: `translateY(${statY}px)`, marginTop: 8, marginBottom: 28,
      }}>
        {hookStatLabel}
      </div>

      {/* Hook text */}
      <div style={{
        fontSize: 26, color: MUTED, textAlign: 'center',
        maxWidth: 760, lineHeight: 1.4, opacity: textIn, padding: '0 40px',
      }}>
        {hookText}
      </div>

      {/* Swipe hint */}
      <div style={{
        position: 'absolute', bottom: 50,
        fontSize: 20, color: GOLD, fontWeight: 700,
        letterSpacing: '2px', opacity: textIn,
      }}>
        DESLIZA →
      </div>
    </AbsoluteFill>
  );
};

const VeoScene: React.FC<{ src: string }> = ({ src }) => (
  <AbsoluteFill>
    <OffthreadVideo src={staticFile(src)} style={{ width: '100%', height: '100%', objectFit: 'cover' }} volume={0} />
    {/* Slight dark vignette for caption readability */}
    <div style={{
      position: 'absolute', inset: 0,
      background: 'linear-gradient(to bottom, rgba(0,0,0,0.15) 0%, rgba(0,0,0,0) 40%, rgba(0,0,0,0.3) 80%)',
    }} />
    {/* Gold left bar */}
    <div style={{ position: 'absolute', left: 0, top: 0, bottom: 0, width: 6, background: GOLD }} />
    <Logo />
  </AbsoluteFill>
);

const Captions: React.FC<{ captions: Caption[] }> = ({ captions }) => {
  const frame = useCurrentFrame();
  const current = captions.find(c =>
    frame >= Math.round(c.startSec * 30) && frame <= Math.round(c.endSec * 30)
  );
  if (!current) return null;
  const sf = Math.round(current.startSec * 30);
  const opacity = interpolate(frame, [sf, sf + 5], [0, 1], { extrapolateRight: 'clamp' });

  return (
    <div style={{
      position: 'absolute', bottom: 130, left: 0, right: 0,
      display: 'flex', justifyContent: 'center', zIndex: 300, opacity,
    }}>
      <div style={{
        background: 'rgba(15,17,21,0.85)',
        borderBottom: `5px solid ${GOLD}`,
        borderRadius: 14, padding: '16px 32px',
        maxWidth: 920, textAlign: 'center',
        fontFamily: 'Arial Black, Arial, sans-serif',
        fontSize: 46, fontWeight: 900, color: WHITE,
        lineHeight: 1.2, letterSpacing: '-0.5px',
        textShadow: '0 2px 10px rgba(0,0,0,0.9)',
      }}>
        {current.text}
      </div>
    </div>
  );
};

// ─── ANNOTATION OVERLAY — narration-synced visual elements ───────────────
// Auto-generated from ElevenLabs word timestamps by annotation_system.py
// Each annotation type animates in with a spring pop-in, holds, then fades.
const AnnotationOverlay: React.FC<{ annotations: Annotation[] }> = ({ annotations }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const active = annotations.filter(a =>
    frame >= a.startSec * fps - 2 && frame <= a.endSec * fps
  );

  return (
    <AbsoluteFill style={{ pointerEvents: 'none', zIndex: 200 }}>
      {active.map((ann, i) => {
        const relFrame = Math.max(0, frame - ann.startSec * fps);
        const totalFrames = (ann.endSec - ann.startSec) * fps;
        const holdFrame = Math.min(relFrame, 18);
        const popScale = spring({ frame: holdFrame, fps, config: { damping: 9, stiffness: 220 } });
        const fadeProgress = Math.max(0, (relFrame - totalFrames * 0.82) / (totalFrames * 0.18));
        const opacity = Math.max(0, 1 - fadeProgress);

        if (ann.type === 'stat_burst') {
          return (
            <div key={i} style={{
              position: 'absolute', left: 0, right: 0, top: '22%',
              display: 'flex', justifyContent: 'center', alignItems: 'center',
              opacity, transform: `scale(${popScale})`,
            }}>
              <div style={{
                fontSize: 180, fontWeight: 900, color: ann.color || GOLD,
                textShadow: `0 0 60px ${ann.color || GOLD}88, 0 8px 30px rgba(0,0,0,0.8)`,
                background: 'rgba(15,17,21,0.72)',
                padding: '10px 50px', borderRadius: 24,
                fontFamily: 'Arial Black, sans-serif',
                letterSpacing: '-2px',
              }}>
                {ann.value}
              </div>
            </div>
          );
        }

        if (ann.type === 'warning_pop') {
          return (
            <div key={i} style={{
              position: 'absolute', left: 36, top: '18%',
              opacity, transform: `scale(${popScale})`, transformOrigin: 'left center',
            }}>
              <div style={{
                background: '#ef4444',
                borderRadius: 20, padding: '16px 36px',
                fontFamily: 'Arial Black, sans-serif', textAlign: 'center',
              }}>
                <div style={{ fontSize: 40, fontWeight: 900, color: WHITE }}>{ann.value}</div>
                {ann.label && (
                  <div style={{ fontSize: 24, color: 'rgba(255,255,255,0.85)', fontWeight: 400 }}>{ann.label}</div>
                )}
              </div>
            </div>
          );
        }

        if (ann.type === 'icon_pop') {
          return (
            <div key={i} style={{
              position: 'absolute', right: 32, top: '30%',
              opacity, transform: `scale(${popScale})`, transformOrigin: 'right center',
              display: 'flex', flexDirection: 'column', alignItems: 'center',
            }}>
              <div style={{
                background: 'rgba(15,17,21,0.88)',
                border: `3px solid ${ann.color || GOLD}`,
                borderRadius: 24, padding: '20px 28px',
                minWidth: 160, textAlign: 'center',
              }}>
                <div style={{ fontSize: 80, lineHeight: 1, marginBottom: 8 }}>{ann.value}</div>
                {ann.label && (
                  <div style={{
                    fontSize: 28, fontWeight: 900, color: ann.color || GOLD,
                    fontFamily: 'Arial Black, sans-serif', letterSpacing: '1px',
                  }}>
                    {ann.label?.toUpperCase()}
                  </div>
                )}
              </div>
            </div>
          );
        }

        if (ann.type === 'timer_pop') {
          return (
            <div key={i} style={{
              position: 'absolute', right: 32, top: '38%',
              opacity, transform: `scale(${popScale})`, transformOrigin: 'right center',
            }}>
              <div style={{
                background: 'rgba(15,17,21,0.88)',
                border: `3px solid ${ann.color || GOLD}`,
                borderRadius: 20, padding: '16px 28px',
                minWidth: 180, textAlign: 'center',
                fontFamily: 'Arial Black, sans-serif',
              }}>
                <div style={{ fontSize: 64 }}>{ann.value}</div>
                {ann.label && (
                  <div style={{ fontSize: 36, fontWeight: 900, color: ann.color || GOLD }}>{ann.label}</div>
                )}
              </div>
            </div>
          );
        }

        if (ann.type === 'step_badge') {
          return (
            <div key={i} style={{
              position: 'absolute', left: 32, top: '32%',
              opacity, transform: `scale(${popScale})`, transformOrigin: 'left center',
              display: 'flex', alignItems: 'center', gap: 20,
            }}>
              <div style={{
                width: 100, height: 100, borderRadius: '50%',
                background: GOLD, display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 64, fontWeight: 900, color: BG,
                fontFamily: 'Arial Black, sans-serif',
                boxShadow: `0 0 30px ${GOLD}66`,
              }}>
                {ann.value}
              </div>
              {ann.label && (
                <div style={{
                  fontSize: 30, fontWeight: 900, color: WHITE,
                  fontFamily: 'Arial Black, sans-serif', maxWidth: 240,
                }}>
                  {ann.label?.toUpperCase()}
                </div>
              )}
            </div>
          );
        }

        return null;
      })}
    </AbsoluteFill>
  );
};

const CTACard: React.FC<{ ctaLine1?: string; educational?: boolean }> = ({ ctaLine1, educational }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const scale = spring({ frame, fps, config: { damping: 12 } });
  const textIn = interpolate(frame, [18, 38], [0, 1], { extrapolateRight: 'clamp' });
  const bounce = spring({ frame: Math.max(0, frame - 30), fps, config: { damping: 8, stiffness: 200 } });

  if (educational) {
    return (
      <AbsoluteFill style={{
        background: BG,
        display: 'flex', flexDirection: 'column',
        alignItems: 'center', justifyContent: 'center',
        fontFamily: 'Arial Black, Arial, sans-serif',
      }}>
        <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 6, background: GOLD }} />

        {/* Animated bell icon */}
        <div style={{
          fontSize: 120, transform: `scale(${bounce})`,
          marginBottom: 24, lineHeight: 1,
        }}>
          🔔
        </div>

        {/* Big action text */}
        <div style={{
          fontSize: 68, fontWeight: 900, color: GOLD,
          letterSpacing: '-1px', textAlign: 'center',
          opacity: textIn, marginBottom: 16,
          textShadow: '0 4px 20px rgba(197,160,89,0.4)',
        }}>
          SUSCRÍBETE
        </div>

        <div style={{
          fontSize: 28, color: WHITE, textAlign: 'center',
          maxWidth: 820, lineHeight: 1.4, opacity: textIn,
          marginBottom: 48, fontWeight: 400, padding: '0 60px',
        }}>
          {ctaLine1 || 'Cada semana: tips reales para captar más clientes'}
        </div>

        {/* Like + share row */}
        <div style={{
          display: 'flex', gap: 40, opacity: textIn,
          marginBottom: 32,
        }}>
          {['👍 LIKE', '💾 GUARDA', '📤 COMPARTE'].map((label) => (
            <div key={label} style={{
              fontSize: 26, fontWeight: 900, color: BG,
              background: GOLD, padding: '16px 32px', borderRadius: 50,
            }}>
              {label}
            </div>
          ))}
        </div>

        <div style={{
          fontSize: 22, color: MUTED, opacity: textIn,
          letterSpacing: '0.5px',
        }}>
          si este tip te fue útil 👇
        </div>

        <div style={{
          position: 'absolute', bottom: 50,
          fontSize: 20, color: GOLD, fontWeight: 700,
          opacity: textIn, letterSpacing: '1px',
        }}>
          ¿Qué tema quieres ver la próxima semana?
        </div>
      </AbsoluteFill>
    );
  }

  return (
    <AbsoluteFill style={{
      background: BG,
      display: 'flex', flexDirection: 'column',
      alignItems: 'center', justifyContent: 'center',
      fontFamily: 'Arial Black, Arial, sans-serif',
    }}>
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 6, background: GOLD }} />

      {/* Big Logo */}
      <div style={{ display: 'flex', alignItems: 'baseline', transform: `scale(${scale})`, marginBottom: 48 }}>
        <span style={{ fontWeight: 900, fontSize: 88, color: GOLD }}>Jego</span>
        <span style={{ fontWeight: 900, fontSize: 88, color: WHITE }}>Digital</span>
      </div>

      <div style={{
        fontSize: 30, color: WHITE, textAlign: 'center',
        maxWidth: 820, lineHeight: 1.4, opacity: textIn,
        marginBottom: 48, fontWeight: 400, padding: '0 40px',
      }}>
        {ctaLine1 || '¿Tu inmobiliaria pierde leads? Hablemos.'}
      </div>

      {/* Gold pill */}
      <div style={{
        background: GOLD, color: BG,
        fontSize: 28, fontWeight: 900,
        padding: '22px 60px', borderRadius: 60,
        opacity: textIn, marginBottom: 22,
      }}>
        jegodigital.com
      </div>

      <div style={{ fontSize: 22, color: MUTED, opacity: textIn }}>
        WhatsApp: +52 998 787 5321
      </div>

      <div style={{
        position: 'absolute', bottom: 50,
        fontSize: 20, color: GOLD, fontWeight: 700,
        opacity: textIn, letterSpacing: '1px',
      }}>
        🔔 SUSCRÍBETE para más estrategias
      </div>
    </AbsoluteFill>
  );
};

// ─── MAIN — 57 seconds @ 30fps = 1710 frames ───
// [0-90]   Hook card (3s)
// [90-750] Veo clip 1 (22s) + VO starts
// [750-1410] Veo clip 2 (22s) + VO continues
// [1410-1710] CTA card (10s)
export const YoutubeShort: React.FC<ShortProps> = ({
  hookStat, hookStatLabel, hookText, hookPillar,
  clip1, clip2, voiceover, captions, annotations = [], ctaLine1, educational,
}) => {
  const HOOK = 90;
  const CLIP = 660;
  const CTA = 300;

  return (
    <AbsoluteFill style={{ background: BG }}>
      <Sequence from={0} durationInFrames={HOOK}>
        <HookCard hookStat={hookStat} hookStatLabel={hookStatLabel} hookText={hookText} hookPillar={hookPillar} />
      </Sequence>

      <Sequence from={HOOK} durationInFrames={CLIP}>
        <VeoScene src={clip1} />
      </Sequence>

      <Sequence from={HOOK + CLIP} durationInFrames={CLIP}>
        <VeoScene src={clip2} />
      </Sequence>

      <Sequence from={HOOK + CLIP * 2} durationInFrames={CTA}>
        <CTACard ctaLine1={ctaLine1} educational={educational} />
      </Sequence>

      {/* Voiceover over both clips */}
      <Sequence from={HOOK} durationInFrames={CLIP * 2}>
        <Audio src={staticFile(voiceover)} volume={1} />
      </Sequence>

      {/* Captions — absolute frame timing already encoded in caption data */}
      <Sequence from={HOOK} durationInFrames={CLIP * 2}>
        <Captions captions={captions} />
      </Sequence>

      {/* Annotation overlays — narration-synced, auto-generated by annotation_system.py */}
      {annotations.length > 0 && (
        <Sequence from={HOOK} durationInFrames={CLIP * 2}>
          <AnnotationOverlay annotations={annotations} />
        </Sequence>
      )}
    </AbsoluteFill>
  );
};
