// AUTO-GENERATED from leads/cold_call_LINKEDIN_2026-04-29.csv on 2026-04-30
// 79 unique-phone leads from LinkedIn-sourced MX real estate decision-makers
module.exports = [
  {
    "phone": "+529842705274",
    "first_name": "David",
    "last_name": "Kaplan",
    "name": "David Kaplan",
    "email": "david@lovetulum.mx",
    "company": "Love Tulum Eco Developments",
    "city": "Tulum",
    "position": "Co-Founder",
    "score": 86,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529982931591",
    "first_name": "Rosalia",
    "last_name": "Cosio",
    "name": "Rosalia Cosio",
    "email": "rosalia@preferredrealestate.com.mx",
    "company": "Preferred Luxury Real Estate",
    "city": "Cancun",
    "position": "Founder",
    "score": 86,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+521527877440",
    "first_name": "Francisco",
    "last_name": "Garciazarco Sánchez",
    "name": "Francisco Garciazarco Sánchez",
    "email": "francisco@espaciosinmobiliarios.mx",
    "company": "Espacios Inmobiliarios",
    "city": "",
    "position": "Director Comercial y socio fundador",
    "score": 81,
    "linkedin_url": "https://mx.linkedin.com/in/francisco-garciazarco-s%C3%A1nchez-8bb4a523",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529981088504",
    "first_name": "Carlos",
    "last_name": "Ortiz",
    "name": "Carlos Ortiz",
    "email": "carlos.ortiz@gruposalo.com",
    "company": "Grupo SALO Inmobiliario",
    "city": "Cancun",
    "position": "Chief Executive Officer",
    "score": 78,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526193520721",
    "first_name": "Jesus",
    "last_name": "Alapisco",
    "name": "Jesus Alapisco",
    "email": "jesus@outliance.com",
    "company": "Jesus Valenzuela, Outliance Real Estate in Los Cabos",
    "city": "Los Cabos",
    "position": "Founder",
    "score": 78,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528002274000",
    "first_name": "Rodrigo",
    "last_name": "Padilla Quiroz",
    "name": "Rodrigo Padilla Quiroz",
    "email": "rodrigo@bim.mx",
    "company": "Banco Inmobiliario Mexicano",
    "city": "",
    "position": "Director general",
    "score": 74,
    "linkedin_url": "https://www.linkedin.com/in/rodrigo-padilla-quiroz-761800125",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529848025076",
    "first_name": "Belky",
    "last_name": "Gomez",
    "name": "Belky Gomez",
    "email": "belky@dreambuilt.mx",
    "company": "Dreambuilt Luxury Real Estate",
    "city": "Tulum",
    "position": "Residential Properties Director",
    "score": 73,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529841421393",
    "first_name": "Álvaro",
    "last_name": "Broch",
    "name": "Álvaro Broch",
    "email": "alvaro@circlegroup.com.mx",
    "company": "Circle Realty Group",
    "city": "Tulum",
    "position": "Marketing Director",
    "score": 73,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529998286807",
    "first_name": "Rodrigo",
    "last_name": "Espinosa",
    "name": "Rodrigo Espinosa",
    "email": "rodrigoespinosa@grupolibera.mx",
    "company": "Grupo Libera",
    "city": "Merida",
    "position": "Marketing Director",
    "score": 73,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523223239442",
    "first_name": "Graciano",
    "last_name": "Valalrta",
    "name": "Graciano Valalrta",
    "email": "graciano@trendsrealestate.com.mx",
    "company": "Trends Real Estate Bienes Raíces Puerto Vallarta",
    "city": "Puerto Vallarta",
    "position": "Real Estate Operations Director",
    "score": 73,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528119687746",
    "first_name": "Hernan",
    "last_name": "Montemayor",
    "name": "Hernan Montemayor",
    "email": "hernan.montemayor@rocadesarrollos.com",
    "company": "ROCA DESARROLLOS",
    "city": "",
    "position": "Chief Executive Officer",
    "score": 73,
    "linkedin_url": "https://mx.linkedin.com/in/hernan-montemayor-402bb18",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+525524538824",
    "first_name": "Ricardo",
    "last_name": "Ballesteros",
    "name": "Ricardo Ballesteros",
    "email": "ricardo@mxdesarrollos.com",
    "company": "MX Desarrollos",
    "city": "",
    "position": "CEO Mxdesarrollos",
    "score": 73,
    "linkedin_url": "https://mx.linkedin.com/in/ricardo-ballesteros-5329a3230",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+521494557713",
    "first_name": "Eduardo",
    "last_name": "Cojab",
    "name": "Eduardo Cojab",
    "email": "",
    "company": "Jysa grupo inmobiliario",
    "city": "",
    "position": "공동 chief executive officer",
    "score": 73,
    "linkedin_url": "linkedin.com/in/ACoAADVTtGoBsBh-WDErw1nnB_2eoOKWZ1Et1yw",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+522137337101",
    "first_name": "Luis",
    "last_name": "G Méndez Trillo",
    "name": "Luis G Méndez Trillo",
    "email": "",
    "company": "Coldwell banker commercial méxico",
    "city": "",
    "position": "Presidente",
    "score": 73,
    "linkedin_url": "linkedin.com/in/ACoAABS7UM4B9Kc2gkhLyPF7vMIstnlqb7qmgsE",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+521258004046",
    "first_name": "Oscar",
    "last_name": "Chapa",
    "name": "Oscar Chapa",
    "email": "",
    "company": "Destiny real estate méxico",
    "city": "",
    "position": "Chief executive officer & founder",
    "score": 73,
    "linkedin_url": "linkedin.com/in/ACoAAAdpQYEBlfLkAJgiVfBSzLBiWx8Heq8wIyI",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+524845505054",
    "first_name": "Pedro",
    "last_name": "De Los Santos A.",
    "name": "Pedro De Los Santos A.",
    "email": "",
    "company": "Nest real estate developer",
    "city": "",
    "position": "Socio fundador",
    "score": 73,
    "linkedin_url": "linkedin.com/in/ACoAAAzuBa0BYmOEYfgBElJxLGBHRhu2JTeQHrY",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+525634071607",
    "first_name": "Elizabeth",
    "last_name": "Duswalt",
    "name": "Elizabeth Duswalt",
    "email": "elizabeth.duswalt@tiktok.com",
    "company": "DOMUM BUSINESS INMOBILIARIO",
    "city": "CDMX",
    "position": "Director of Global Brand Partnerships",
    "score": 71,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529994866941",
    "first_name": "Wendy",
    "last_name": "Segura",
    "name": "Wendy Segura",
    "email": "wendy@sendabienesraices.com",
    "company": "Senda Bienes Raíces",
    "city": "Merida",
    "position": "Partner and Administration Manager",
    "score": 71,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528121465638",
    "first_name": "Andres",
    "last_name": "Gonzalez",
    "name": "Andres Gonzalez",
    "email": "andres.gonzalez@gpv.com.mx",
    "company": "GP Vivienda",
    "city": "",
    "position": "Director de Administracion y Finanzas",
    "score": 68,
    "linkedin_url": "https://mx.linkedin.com/in/andres-gonzalez-85432b7",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523325943600",
    "first_name": "Lorenza",
    "last_name": "Padilla",
    "name": "Lorenza Padilla",
    "email": "lpc@casasdomus.com.mx",
    "company": "DOMUS DESARROLLADORA INMOBILIARA SA DE CV",
    "city": "",
    "position": "DIRECTORA ADMINISTRATIVA",
    "score": 68,
    "linkedin_url": "https://mx.linkedin.com/in/lorenza-padilla-b3539b57",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+527008424603",
    "first_name": "Fernando",
    "last_name": "Vega Espinosa",
    "name": "Fernando Vega Espinosa",
    "email": "fernando.espinosa@inmove.com.mx",
    "company": "INMOVE Desarrollos Inmobiliarios",
    "city": "",
    "position": "Director",
    "score": 68,
    "linkedin_url": "https://mx.linkedin.com/in/fernando-vega-espinosa",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528124053510",
    "first_name": "Nicolas",
    "last_name": "Andrade Gutierrez",
    "name": "Nicolas Andrade Gutierrez",
    "email": "nicolas@dipz.mx",
    "company": "Dipz Desarrollos",
    "city": "",
    "position": "Director de construcción",
    "score": 68,
    "linkedin_url": "https://mx.linkedin.com/in/nicolas-henri-andrade-gutierrez-b3475553",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528715709538",
    "first_name": "Rogelio",
    "last_name": "Díaz de León",
    "name": "Rogelio Díaz de León",
    "email": "rogelio@coeza.mx",
    "company": "Coeza Desarrollos",
    "city": "",
    "position": "Director de proyectos",
    "score": 68,
    "linkedin_url": "https://mx.linkedin.com/in/rogelioddl",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+525555201000",
    "first_name": "Genaro",
    "last_name": "Moreno",
    "name": "Genaro Moreno",
    "email": "genaro.moreno@delparque.com.mx",
    "company": "Del Parque Desarrolladora",
    "city": "",
    "position": "Director Comercial",
    "score": 68,
    "linkedin_url": "https://www.linkedin.com/in/genaro-moreno-93a1a731",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528113664100",
    "first_name": "Dieter",
    "last_name": "Lorenzen",
    "name": "Dieter Lorenzen",
    "email": "dl@lomadesarrollos.mx",
    "company": "LOMA Desarrollos",
    "city": "",
    "position": "Director ejecutivo",
    "score": 68,
    "linkedin_url": "https://www.linkedin.com/in/dieterlorenzen",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528112345678",
    "first_name": "Miguel",
    "last_name": "Armendariz",
    "name": "Miguel Armendariz",
    "email": "miguel.armendariz@gpdesarrollos.com.mx",
    "company": "GP Desarrollos",
    "city": "",
    "position": "Director de operaciones",
    "score": 68,
    "linkedin_url": "https://www.linkedin.com/in/miguel-a-armendariz-aa9064ab",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+527094065800",
    "first_name": "Rodrigo",
    "last_name": "Torre",
    "name": "Rodrigo Torre",
    "email": "r.torre@everland.mx",
    "company": "Everland - Real Estate Development",
    "city": "",
    "position": "Director Comercial",
    "score": 68,
    "linkedin_url": "https://www.linkedin.com/in/rodrigotorre",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+524428902598",
    "first_name": "Charles",
    "last_name": "Elmann Fasja",
    "name": "Charles Elmann Fasja",
    "email": "",
    "company": "Parks desarrolladora",
    "city": "",
    "position": "Director general",
    "score": 66,
    "linkedin_url": "linkedin.com/in/ACoAAB0kMcIBETCzrdGDsHOpzoxoJKF-BzUNl5o",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523336732616",
    "first_name": "Ignacio",
    "last_name": "Vivanco Valles",
    "name": "Ignacio Vivanco Valles",
    "email": "",
    "company": "Garvi grupo inmobiliario",
    "city": "",
    "position": "Director general",
    "score": 66,
    "linkedin_url": "linkedin.com/in/ACoAAAgdSnQBy-ZC8X3QSpQBi1JORWSXrWrH_mc",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+525540001351",
    "first_name": "Alberto",
    "last_name": "Antonio Colorado Ferman",
    "name": "Alberto Antonio Colorado Ferman",
    "email": "",
    "company": "Co83 inmobiliaria and constructora de cv",
    "city": "",
    "position": "Director general",
    "score": 66,
    "linkedin_url": "linkedin.com/in/ACoAAArtwT0BAlodIgEgSBCxaftX1ddXtoWlgSM",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529842673242",
    "first_name": "Ivan",
    "last_name": "Ferrer",
    "name": "Ivan Ferrer",
    "email": "",
    "company": "Gmb real estate",
    "city": "",
    "position": "Director general",
    "score": 66,
    "linkedin_url": "linkedin.com/in/ACoAABEQO4gBZzlN3NL0deaUOVhC6ruiAyAEtEY",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+525510002137",
    "first_name": "Saleh",
    "last_name": "Urfali Salame",
    "name": "Saleh Urfali Salame",
    "email": "",
    "company": "Inmobiliaria best lands de cv",
    "city": "",
    "position": "Director general",
    "score": 66,
    "linkedin_url": "linkedin.com/in/ACoAAAMssGsBwzUhkXvQ82ymBaEF2BpGZf5FFoA",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529841798042",
    "first_name": "Bibiana",
    "last_name": "Fidalgo",
    "name": "Bibiana Fidalgo",
    "email": "bibiana@selectrealtymexico.com",
    "company": "Select Realty Mexico",
    "city": "Playa del Carmen",
    "position": "Manager",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529848794858",
    "first_name": "Albane",
    "last_name": "Mellec",
    "name": "Albane Mellec",
    "email": "albane@c21caribbean.com",
    "company": "Century 21 Caribbean Paradise Real Estate en Playa del Carmen",
    "city": "Playa del Carmen",
    "position": "Branch Manager",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529842090644",
    "first_name": "Paola",
    "last_name": "Barrera",
    "name": "Paola Barrera",
    "email": "paola@jaguartulum.com",
    "company": "Jaguar Tulum Real Estate",
    "city": "Tulum",
    "position": "Sales Director",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523158881298",
    "first_name": "Agustin",
    "last_name": "Leone",
    "name": "Agustin Leone",
    "email": "agustin@tulumlandandproperty.com",
    "company": "Tulum Land & Property | Real Estate",
    "city": "Tulum",
    "position": "Marketing Director",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529842148038",
    "first_name": "Allan",
    "last_name": "Lockhart",
    "name": "Allan Lockhart",
    "email": "allan@nasplaya.com",
    "company": "North American Standards Property Management, Rentals, Real Estate & Realtors",
    "city": "Playa del Carmen",
    "position": "Manager",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529999005799",
    "first_name": "Alejandro",
    "last_name": "Castro",
    "name": "Alejandro Castro",
    "email": "alejandro@inmobiliariamerida.com",
    "company": "IM Propiedades en Renta",
    "city": "Merida",
    "position": "Manager",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526241430372",
    "first_name": "Brian",
    "last_name": "Westerlund",
    "name": "Brian Westerlund",
    "email": "brian@diamanterealtors.com",
    "company": "Diamante Realtors",
    "city": "Los Cabos",
    "position": "Sales Manager",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526242255765",
    "first_name": "Michael",
    "last_name": "Mattos",
    "name": "Michael Mattos",
    "email": "michael@caboproperties.com",
    "company": "Cabo Properties",
    "city": "Los Cabos",
    "position": "Marketing Director",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526242184534",
    "first_name": "Alex",
    "last_name": "Hugessen",
    "name": "Alex Hugessen",
    "email": "alex@caborealestate.com",
    "company": "REMexico - Cabo Real Estate",
    "city": "Los Cabos",
    "position": "Director of Marketing",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526241297975",
    "first_name": "Samantha",
    "last_name": "Ross",
    "name": "Samantha Ross",
    "email": "samantha@caborealestateservices.com",
    "company": "Cabo Real Estate Services",
    "city": "Los Cabos",
    "position": "Sales Design And Management",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526241601502",
    "first_name": "Josie",
    "last_name": "García",
    "name": "Josie García",
    "email": "josie@ownincabo.com",
    "company": "Own in Cabo",
    "city": "Los Cabos",
    "position": "Sales Consultant",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526241720069",
    "first_name": "Anabel",
    "last_name": "Suarez",
    "name": "Anabel Suarez",
    "email": "anabel@cabo4sale.com",
    "company": "Cabo4Sale Real Estate",
    "city": "Los Cabos",
    "position": "Broker Assistant",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523222222604",
    "first_name": "Stan",
    "last_name": "Freeman",
    "name": "Stan Freeman",
    "email": "stan.freeman@cblacosta.com",
    "company": "Coldwell Banker La Costa - Olas Altas / Romantic Zone",
    "city": "Puerto Vallarta",
    "position": "Real Estate Manager",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523222449059",
    "first_name": "Gabriel",
    "last_name": "Jones",
    "name": "Gabriel Jones",
    "email": "gabriel@mexhome.com",
    "company": "MexHome Real Estate - Puerto Vallarta",
    "city": "Puerto Vallarta",
    "position": "Talent Acquisition Manager",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523222240014",
    "first_name": "Michael",
    "last_name": "Green",
    "name": "Michael Green",
    "email": "michael@boardwalkrealtypv.com",
    "company": "BOARDWALK REALTY PV",
    "city": "Puerto Vallarta",
    "position": "Broker",
    "score": 65,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529842420075",
    "first_name": "Dimitris",
    "last_name": "Hoffmann",
    "name": "Dimitris Hoffmann",
    "email": "",
    "company": "Maya ocean real estate",
    "city": "",
    "position": "Principal chief executive officer",
    "score": 65,
    "linkedin_url": "linkedin.com/in/ACoAADAcZ34BekIRgkxXbL7crTAwBWrGWsNiCSk",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528110752092",
    "first_name": "Pedro",
    "last_name": "Davila",
    "name": "Pedro Davila",
    "email": "",
    "company": "Quantium desarrollos",
    "city": "",
    "position": "Director general y co-fundador",
    "score": 65,
    "linkedin_url": "linkedin.com/in/ACoAADB4pi4BG3Jf5eHg_cZ3m0Ki4KP_GThmndI",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+527227902615",
    "first_name": "Grabiel",
    "last_name": "Terriquez",
    "name": "Grabiel Terriquez",
    "email": "",
    "company": "Avviare inmobiliaria",
    "city": "",
    "position": "Chief executive officer",
    "score": 65,
    "linkedin_url": "linkedin.com/in/ACoAAAZf0usBcEs9_zQoJ48jgtM0jGg6DbVbT9E",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+524074662475",
    "first_name": "Raul",
    "last_name": "Alberti",
    "name": "Raul Alberti",
    "email": "",
    "company": "195 real estate",
    "city": "",
    "position": "Fundador y chief executive officer",
    "score": 65,
    "linkedin_url": "linkedin.com/in/ACoAACWHbaYBUS-o_xhXpuvKL3-QV9YW5Vn9Hxg",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528120900000",
    "first_name": "Juan",
    "last_name": "Carlos Duran Gomez",
    "name": "Juan Carlos Duran Gomez",
    "email": "",
    "company": "Dm desarrolladora de proyectos",
    "city": "",
    "position": "Chief executive officer",
    "score": 65,
    "linkedin_url": "linkedin.com/in/ACoAAAN3vjQBerO4G-nR_pKY5javR96g6y8SGPA",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523321010135",
    "first_name": "Bruno",
    "last_name": "Martinez",
    "name": "Bruno Martinez",
    "email": "",
    "company": "Kampus desarrollos",
    "city": "",
    "position": "Chief executive officer",
    "score": 65,
    "linkedin_url": "linkedin.com/in/ACoAABih-scBSKN3xhF-xHqkWRRbqyKxJH79Bkc",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+521750359483",
    "first_name": "Karla",
    "last_name": "Flores Certified Mexico Realtor®",
    "name": "Karla Flores Certified Mexico Realtor®",
    "email": "",
    "company": "Nomad realty | certified experts in luxury and sustainable real estate in mexico",
    "city": "",
    "position": "Co-founder & real estate broker",
    "score": 65,
    "linkedin_url": "linkedin.com/in/ACoAAAejPu4B9AAMpLGb6DSBvBHSSDop5Zn_joc",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523341200013",
    "first_name": "Luis",
    "last_name": "Parra G",
    "name": "Luis Parra G",
    "email": "",
    "company": "Forja grupo inmobiliario",
    "city": "",
    "position": "Joint chief executive officer",
    "score": 65,
    "linkedin_url": "linkedin.com/in/ACoAAAxuevwB64wD5VsmXiEGnlV86H5b-81-W0k",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529982274831",
    "first_name": "Monica",
    "last_name": "Elizabeth",
    "name": "Monica Elizabeth",
    "email": "monica@propiedadescancun.mx",
    "company": "Propiedades Cancún",
    "city": "Cancun",
    "position": "",
    "score": 61,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529841072147",
    "first_name": "Fanny",
    "last_name": "Zolli",
    "name": "Fanny Zolli",
    "email": "fanny@ekasa.mx",
    "company": "Ekasa Desarrollos Inmobiliarios",
    "city": "Playa del Carmen",
    "position": "",
    "score": 61,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528117691122",
    "first_name": "Laura",
    "last_name": "Moreno",
    "name": "Laura Moreno",
    "email": "lmoreno@gm22.com.mx",
    "company": "GM22 Bienes Raíces",
    "city": "Monterrey",
    "position": "",
    "score": 61,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526242262215",
    "first_name": "Gaby",
    "last_name": "Menchaca",
    "name": "Gaby Menchaca",
    "email": "gaby@inmueblesloscabos.com.mx",
    "company": "Grupo Inmuebles Los Cabos Real Estate - Inmobiliaria",
    "city": "Los Cabos",
    "position": "",
    "score": 61,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+521281271280",
    "first_name": "Martin",
    "last_name": "Cedillo rosales",
    "name": "Martin Cedillo rosales",
    "email": "martin.rosales@pulsoinmobiliario.com",
    "company": "Pulso Inmobiliario",
    "city": "",
    "position": "Director de proyecto",
    "score": 60,
    "linkedin_url": "https://www.linkedin.com/in/martin-adan-cedillo-rosales-a53423179",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+525510857760",
    "first_name": "Daniel",
    "last_name": "Goldwasser",
    "name": "Daniel Goldwasser",
    "email": "daniel.goldwasser@grupo-eco.com",
    "company": "Grupo Eco Developers",
    "city": "",
    "position": "Director Comercial",
    "score": 60,
    "linkedin_url": "https://mx.linkedin.com/in/daniel-goldwasser-002a79b4",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528116604658",
    "first_name": "Adrian",
    "last_name": "Hidalgo",
    "name": "Adrian Hidalgo",
    "email": "adrian.hidalgo@4srealestate.com",
    "company": "4S Real Estate Foresight",
    "city": "",
    "position": "Chief Commercial Officer (CCO)",
    "score": 60,
    "linkedin_url": "https://mx.linkedin.com/in/ahidalgoreynoso",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+525554805848",
    "first_name": "Mario",
    "last_name": "Calderon",
    "name": "Mario Calderon",
    "email": "mario.calderon@gbm.com",
    "company": "GBM Real Estate",
    "city": "",
    "position": "Director of Investments",
    "score": 60,
    "linkedin_url": "https://www.linkedin.com/in/mariocalderon2014",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529981687178",
    "first_name": "Gabriela",
    "last_name": "Molina",
    "name": "Gabriela Molina",
    "email": "gmolina@invertikal.com",
    "company": "Invertikal Developers",
    "city": "",
    "position": "Director de proyecto",
    "score": 60,
    "linkedin_url": "https://www.linkedin.com/in/gaby-molina",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526937427264",
    "first_name": "Elssy",
    "last_name": "Eyssautier",
    "name": "Elssy Eyssautier",
    "email": "elssy.eyssautier@gdcdesarrollos.com",
    "company": "GDC DESARROLLOS",
    "city": "",
    "position": "Directora de desarrollo inmobiliario",
    "score": 60,
    "linkedin_url": "https://www.linkedin.com/in/elssy-aileen-eyssautier-245094b2",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523318681590",
    "first_name": "Antonio",
    "last_name": "Alejo",
    "name": "Antonio Alejo",
    "email": "",
    "company": "Grupo guía excelencia inmobiliaria",
    "city": "",
    "position": "Chief financial officer",
    "score": 60,
    "linkedin_url": "linkedin.com/in/ACoAAA12XdYBL9plefp4oqmM801t-0iJM2m3oZ4",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+528119720333",
    "first_name": "Jorge",
    "last_name": "Martínez Chávez",
    "name": "Jorge Martínez Chávez",
    "email": "",
    "company": "Capital real estate",
    "city": "",
    "position": "Chief investment officer",
    "score": 60,
    "linkedin_url": "linkedin.com/in/ACoAAAoIjOABSSpv5FybYK6Ie_QCd-Tu8WRCh_A",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529984775050",
    "first_name": "Victor",
    "last_name": "Garcia",
    "name": "Victor Garcia",
    "email": "",
    "company": "Grupo velas desarrollos inmobiliarios",
    "city": "",
    "position": "E-business director",
    "score": 60,
    "linkedin_url": "linkedin.com/in/ACoAAAliWAYBwEE1U-dP1fY6XX3TNFUmHlXb0Gw",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529841762711",
    "first_name": "Rene",
    "last_name": "Villalobos",
    "name": "Rene Villalobos",
    "email": "rene@hometulum.com",
    "company": "Properties in tulum l HOME TULUM REAL ESTATE",
    "city": "Tulum",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529985590044",
    "first_name": "Michelle",
    "last_name": "Romero",
    "name": "Michelle Romero",
    "email": "mromero@highlinemexico.com",
    "company": "Highline México - Real Estate / Inmobiliaria",
    "city": "Tulum",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529986880710",
    "first_name": "Julio",
    "last_name": "Mena",
    "name": "Julio Mena",
    "email": "julio.mena@puertorealty.com",
    "company": "Puerto Realty",
    "city": "Cancun",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529988859022",
    "first_name": "Leticia",
    "last_name": "Vazquez",
    "name": "Leticia Vazquez",
    "email": "leticia.vazquez@century21apolo.com",
    "company": "CENTURY 21 Apolo Cancún",
    "city": "Cancun",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529985001810",
    "first_name": "Lucero",
    "last_name": "Alvarez",
    "name": "Lucero Alvarez",
    "email": "lalvarez@mlcancunrealestate.com",
    "company": "M & L CANCUN REAL ESTATE",
    "city": "Cancun",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529843934177",
    "first_name": "Gabriel",
    "last_name": "Lalancette",
    "name": "Gabriel Lalancette",
    "email": "gabriel@realestateplaya.com",
    "company": "Real Estate Playa",
    "city": "Playa del Carmen",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+529994990919",
    "first_name": "Bittor",
    "last_name": "Zulueta",
    "name": "Bittor Zulueta",
    "email": "bittor.zulueta@colonialmeridarealestate.com",
    "company": "Colonial Merida Real Estate",
    "city": "Merida",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+526241436546",
    "first_name": "Daniel",
    "last_name": "Reyna",
    "name": "Daniel Reyna",
    "email": "danielreyna@remaxsunsetview.com",
    "company": "ReMax Sunset View",
    "city": "Los Cabos",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523222249400",
    "first_name": "Maria",
    "last_name": "Lurdes",
    "name": "Maria Lurdes",
    "email": "maria.lurdes@fpbienesraices.com",
    "company": "FP Bienes Raíces y Soluciones",
    "city": "Puerto Vallarta",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+523331220024",
    "first_name": "Freddy",
    "last_name": "Adrian",
    "name": "Freddy Adrian",
    "email": "freddyadrian@c21continental.com",
    "company": "CENTURY 21 Continental",
    "city": "Guadalajara",
    "position": "",
    "score": 53,
    "linkedin_url": "",
    "source": "linkedin_2026-04-29"
  },
  {
    "phone": "+520822677963",
    "first_name": "Yonatan",
    "last_name": "Lugardo",
    "name": "Yonatan Lugardo",
    "email": "",
    "company": "Ehubs",
    "city": "",
    "position": "Director of operations and real estate",
    "score": 52,
    "linkedin_url": "linkedin.com/in/ACoAAAxwGrgBX3THwUFNIILPUWdlz4ws1pdIWLU",
    "source": "linkedin_2026-04-29"
  }
];
