// AUTO-GENERATED 57 leads from DIAL_READY batch 2026-04-19
module.exports = [
  {
    "phone": "+529982180819",
    "first_name": "Jose",
    "last_name": "Fernandez",
    "email": "jfernandez@vivo.mx",
    "company": "Aloja Cancún",
    "website": "vivo.mx",
    "city": "Cancun",
    "position": "Project Director",
    "google_rating": "4",
    "score": 90
  },
  {
    "phone": "+529841163251",
    "first_name": "Judi",
    "last_name": "Shaw",
    "email": "judi@livingrivieramaya.com",
    "company": "Living Riviera Maya Real Estate",
    "website": "livingrivieramaya.com",
    "city": "Playa del Carmen",
    "position": "Owner",
    "google_rating": "4.9",
    "score": 90
  },
  {
    "phone": "+529842294192",
    "first_name": "Andrea",
    "last_name": "Flores",
    "email": "andrea@evokerealestategroup.com",
    "company": "Evoke Real Estate Group",
    "website": "evokerealestategroup.com",
    "city": "Playa del Carmen",
    "position": "Commercial Director",
    "google_rating": "5",
    "score": 90
  },
  {
    "phone": "+529848794858",
    "first_name": "Albane",
    "last_name": "Mellec",
    "email": "albane@c21caribbean.com",
    "company": "Century 21 Caribbean Paradise Real Estate en Playa del Carmen",
    "website": "c21caribbean.com",
    "city": "Playa del Carmen",
    "position": "Branch Manager",
    "google_rating": "4.4",
    "score": 90
  },
  {
    "phone": "+525633709470",
    "first_name": "Antoine",
    "last_name": "Menudier",
    "email": "a.menudier@lagencemx.com",
    "company": "L'agence by Los Socios",
    "website": "lagencemx.com",
    "city": "Playa del Carmen",
    "position": "Marketing Director",
    "google_rating": "4.9",
    "score": 90
  },
  {
    "phone": "+523223239442",
    "first_name": "Graciano",
    "last_name": "Valalrta",
    "email": "graciano@trendsrealestate.com.mx",
    "company": "Trends Real Estate Bienes Raíces Puerto Vallarta",
    "website": "trendsrealestate.com.mx",
    "city": "Puerto Vallarta",
    "position": "Real Estate Operations Director",
    "google_rating": "5",
    "score": 90
  },
  {
    "phone": "+526242255765",
    "first_name": "Michael",
    "last_name": "Mattos",
    "email": "michael@caboproperties.com",
    "company": "Cabo Properties",
    "website": "caboproperties.com",
    "city": "Los Cabos",
    "position": "Marketing Director",
    "google_rating": "3.5",
    "score": 90
  },
  {
    "phone": "+16193520721",
    "first_name": "Jesus",
    "last_name": "Alapisco",
    "email": "jesus@outliance.com",
    "company": "Jesus Valenzuela, Outliance Real Estate in Los Cabos",
    "website": "outliance.com",
    "city": "Los Cabos",
    "position": "Founder",
    "google_rating": "5",
    "score": 90
  },
  {
    "phone": "+526242184534",
    "first_name": "Alex",
    "last_name": "Hugessen",
    "email": "alex@caborealestate.com",
    "company": "REMexico - Cabo Real Estate",
    "website": "caborealestate.com",
    "city": "Los Cabos",
    "position": "Director of Marketing",
    "google_rating": "4.7",
    "score": 90
  },
  {
    "phone": "+529842090644",
    "first_name": "Paola",
    "last_name": "Barrera",
    "email": "paola@jaguartulum.com",
    "company": "Jaguar Tulum Real Estate",
    "website": "jaguartulum.com",
    "city": "Tulum",
    "position": "Sales Director",
    "google_rating": "4.8",
    "score": 90
  },
  {
    "phone": "+525634071607",
    "first_name": "Elizabeth",
    "last_name": "Duswalt",
    "email": "elizabeth.duswalt@tiktok.com",
    "company": "DOMUM BUSINESS INMOBILIARIO",
    "website": "tiktok.com",
    "city": "CDMX",
    "position": "Director of Global Brand Partnerships",
    "google_rating": "5",
    "score": 90
  },
  {
    "phone": "+529998286807",
    "first_name": "Rodrigo",
    "last_name": "Espinosa",
    "email": "rodrigoespinosa@grupolibera.mx",
    "company": "Grupo Libera",
    "website": "grupolibera.mx",
    "city": "Merida",
    "position": "Marketing Director",
    "google_rating": "4.7",
    "score": 90
  },
  {
    "phone": "+526241430372",
    "first_name": "Brian",
    "last_name": "Westerlund",
    "email": "brian@diamanterealtors.com",
    "company": "Diamante Realtors",
    "website": "diamanterealtors.com",
    "city": "Los Cabos",
    "position": "Sales Manager",
    "google_rating": "4.5",
    "score": 90
  },
  {
    "phone": "+529848025076",
    "first_name": "Belky",
    "last_name": "Gomez",
    "email": "belky@dreambuilt.mx",
    "company": "Dreambuilt Luxury Real Estate",
    "website": "dreambuilt.mx",
    "city": "Tulum",
    "position": "Residential Properties Director",
    "google_rating": "4.6",
    "score": 90
  },
  {
    "phone": "+529842705274",
    "first_name": "David",
    "last_name": "Kaplan",
    "email": "david@lovetulum.mx",
    "company": "Love Tulum Eco Developments",
    "website": "lovetulum.mx",
    "city": "Tulum",
    "position": "Co-Founder",
    "google_rating": "4.9",
    "score": 90
  },
  {
    "phone": "+529842673242",
    "first_name": "Josep",
    "last_name": "Folch",
    "email": "josep@gmb.com.mx",
    "company": "GMB Gama Master Broker",
    "website": "gmb.com.mx",
    "city": "Tulum",
    "position": "Vice President",
    "google_rating": "3.8",
    "score": 90
  },
  {
    "phone": "+529841421393",
    "first_name": "Álvaro",
    "last_name": "Broch",
    "email": "alvaro@circlegroup.com.mx",
    "company": "Circle Realty Group",
    "website": "circlegroup.com.mx",
    "city": "Tulum",
    "position": "Marketing Director",
    "google_rating": "5",
    "score": 90
  },
  {
    "phone": "+529982931591",
    "first_name": "Rosalia",
    "last_name": "Cosio",
    "email": "rosalia@preferredrealestate.com.mx",
    "company": "Preferred Luxury Real Estate",
    "website": "preferredrealestate.com.mx",
    "city": "Cancun",
    "position": "Founder",
    "google_rating": "5",
    "score": 90
  },
  {
    "phone": "+523222222604",
    "first_name": "Stan",
    "last_name": "Freeman",
    "email": "stan.freeman@cblacosta.com",
    "company": "Coldwell Banker La Costa - Olas Altas / Romantic Zone",
    "website": "cblacosta.com",
    "city": "Puerto Vallarta",
    "position": "Real Estate Manager",
    "google_rating": "4.9",
    "score": 90
  },
  {
    "phone": "+523222449059",
    "first_name": "Gabriel",
    "last_name": "Jones",
    "email": "gabriel@mexhome.com",
    "company": "MexHome Real Estate - Puerto Vallarta",
    "website": "mexhome.com",
    "city": "Puerto Vallarta",
    "position": "Talent Acquisition Manager",
    "google_rating": "5",
    "score": 90
  },
  {
    "phone": "+523222240014",
    "first_name": "Michael",
    "last_name": "Green",
    "email": "michael@boardwalkrealtypv.com",
    "company": "BOARDWALK REALTY PV",
    "website": "boardwalkrealtypv.com",
    "city": "Puerto Vallarta",
    "position": "Broker",
    "google_rating": "4.9",
    "score": 90
  },
  {
    "phone": "+529842148038",
    "first_name": "Allan",
    "last_name": "Lockhart",
    "email": "allan@nasplaya.com",
    "company": "North American Standards Property Management, Rentals, Real Estate & Realtors",
    "website": "nasplaya.com",
    "city": "Playa del Carmen",
    "position": "Manager",
    "google_rating": "4.7",
    "score": 85
  },
  {
    "phone": "+529999005799",
    "first_name": "Alejandro",
    "last_name": "Castro",
    "email": "alejandro@inmobiliariamerida.com",
    "company": "IM Propiedades en Renta",
    "website": "inmobiliariamerida.com",
    "city": "Merida",
    "position": "Manager",
    "google_rating": "4.9",
    "score": 85
  },
  {
    "phone": "+529841798042",
    "first_name": "Bibiana",
    "last_name": "Fidalgo",
    "email": "bibiana@selectrealtymexico.com",
    "company": "Select Realty Mexico",
    "website": "selectrealtymexico.com",
    "city": "Playa del Carmen",
    "position": "Manager",
    "google_rating": "4.5",
    "score": 85
  },
  {
    "phone": "+13158881298",
    "first_name": "Agustin",
    "last_name": "Leone",
    "email": "agustin@tulumlandandproperty.com",
    "company": "Tulum Land & Property | Real Estate",
    "website": "tulumlandandproperty.com",
    "city": "Tulum",
    "position": "Marketing Director",
    "google_rating": "5",
    "score": 85
  },
  {
    "phone": "+526241720069",
    "first_name": "Anabel",
    "last_name": "Suarez",
    "email": "anabel@cabo4sale.com",
    "company": "Cabo4Sale Real Estate",
    "website": "cabo4sale.com",
    "city": "Los Cabos",
    "position": "Broker Assistant",
    "google_rating": "4.8",
    "score": 85
  },
  {
    "phone": "+529848733028",
    "first_name": "Hazel",
    "last_name": "Richardson",
    "email": "hazel@remaxmaya.com",
    "company": "Remax Maya Real Estate in Playa del Carmen and Riviera Maya",
    "website": "remaxmaya.com",
    "city": "Playa del Carmen",
    "position": "Real Estate Agent",
    "google_rating": "4.9",
    "score": 65
  },
  {
    "phone": "+529999262839",
    "first_name": "Enrique",
    "last_name": "Servin",
    "email": "enrique@century21galaxy.com",
    "company": "Century 21 Galaxy",
    "website": "century21galaxy.com",
    "city": "Merida",
    "position": "Intern",
    "google_rating": "4.1",
    "score": 65
  },
  {
    "phone": "+526241224063",
    "first_name": "Javier",
    "last_name": "Orozco",
    "email": "javier@casasfebo.com",
    "company": "Casas Febo Inmobiliaria",
    "website": "casasfebo.com",
    "city": "Los Cabos",
    "position": "Real Estate Agent",
    "google_rating": "4.8",
    "score": 65
  },
  {
    "phone": "+529996358100",
    "first_name": "Elsy",
    "last_name": "Rouco",
    "email": "elsy@mudarseamerida.com",
    "company": "mudarseamerida.com",
    "website": "mudarseamerida.com",
    "city": "Merida",
    "position": "Wealth Advisor",
    "google_rating": "4.8",
    "score": 65
  },
  {
    "phone": "+526241431341",
    "first_name": "Vincent",
    "last_name": "Swanlund",
    "email": "vswanlund@cbriveras.com",
    "company": "Coldwell Banker Riveras",
    "website": "cbriveras.com",
    "city": "Los Cabos",
    "position": "Real Estate Agent",
    "google_rating": "4.7",
    "score": 65
  },
  {
    "phone": "+529981465154",
    "first_name": "Adriana",
    "last_name": "Lopez",
    "email": "alopez@eproperties.mx",
    "company": "Eproperties - Luxury Real Estate, México.",
    "website": "eproperties.mx",
    "city": "Cancun",
    "position": "Real Estate Advisor",
    "google_rating": "5",
    "score": 65
  },
  {
    "phone": "+526241601502",
    "first_name": "Josie",
    "last_name": "García",
    "email": "josie@ownincabo.com",
    "company": "Own in Cabo",
    "website": "ownincabo.com",
    "city": "Los Cabos",
    "position": "Sales Consultant",
    "google_rating": "4.8",
    "score": 65
  },
  {
    "phone": "+529982274831",
    "first_name": "Monica",
    "last_name": "Elizabeth",
    "email": "monica@propiedadescancun.mx",
    "company": "Propiedades Cancún",
    "website": "propiedadescancun.mx",
    "city": "Cancun",
    "position": "",
    "google_rating": "4.4",
    "score": 60
  },
  {
    "phone": "+529986880710",
    "first_name": "Julio",
    "last_name": "Mena",
    "email": "julio.mena@puertorealty.com",
    "company": "Puerto Realty",
    "website": "puertorealty.com",
    "city": "Cancun",
    "position": "",
    "google_rating": "4.7",
    "score": 60
  },
  {
    "phone": "+529843934177",
    "first_name": "Gabriel",
    "last_name": "Lalancette",
    "email": "gabriel@realestateplaya.com",
    "company": "Real Estate Playa",
    "website": "realestateplaya.com",
    "city": "Playa del Carmen",
    "position": "",
    "google_rating": "5",
    "score": 60
  },
  {
    "phone": "+529841573402",
    "first_name": "Jessica",
    "last_name": "Calderon",
    "email": "jessica@5thaverealtygroup.com",
    "company": "5th Avenue Realty Playa del Carmen",
    "website": "5thaverealtygroup.com",
    "city": "Playa del Carmen",
    "position": "Buyer",
    "google_rating": "4.1",
    "score": 60
  },
  {
    "phone": "+529841072147",
    "first_name": "Fanny",
    "last_name": "Zolli",
    "email": "fanny@ekasa.mx",
    "company": "Ekasa Desarrollos Inmobiliarios",
    "website": "ekasa.mx",
    "city": "Playa del Carmen",
    "position": "",
    "google_rating": "5",
    "score": 60
  },
  {
    "phone": "+529841057152",
    "first_name": "Jose",
    "last_name": "Assad",
    "email": "jassad@playainvestments.mx",
    "company": "Playa Investments",
    "website": "playainvestments.mx",
    "city": "Playa del Carmen",
    "position": "Content Management",
    "google_rating": "5",
    "score": 60
  },
  {
    "phone": "+529841198165",
    "first_name": "Erika",
    "last_name": "Vizcarra",
    "email": "erika@geckocaribbean.com",
    "company": "Gecko Caribbean",
    "website": "geckocaribbean.com",
    "city": "Playa del Carmen",
    "position": "Developer",
    "google_rating": "4.9",
    "score": 60
  },
  {
    "phone": "+523331220024",
    "first_name": "Freddy",
    "last_name": "Adrian",
    "email": "freddyadrian@c21continental.com",
    "company": "CENTURY 21 Continental",
    "website": "c21continental.com",
    "city": "Guadalajara",
    "position": "",
    "google_rating": "4.3",
    "score": 60
  },
  {
    "phone": "+526242262215",
    "first_name": "Gaby",
    "last_name": "Menchaca",
    "email": "gaby@inmueblesloscabos.com.mx",
    "company": "Grupo Inmuebles Los Cabos Real Estate - Inmobiliaria",
    "website": "inmueblesloscabos.com.mx",
    "city": "Los Cabos",
    "position": "",
    "google_rating": "5",
    "score": 60
  },
  {
    "phone": "+526246889619",
    "first_name": "Abril",
    "last_name": "Pola",
    "email": "abrilpola@eliterealestateloscabos.com",
    "company": "Elite Real Estate Los Cabos",
    "website": "eliterealestateloscabos.com",
    "city": "Los Cabos",
    "position": "Realtor",
    "google_rating": "5",
    "score": 60
  },
  {
    "phone": "+526241297975",
    "first_name": "Samantha",
    "last_name": "Ross",
    "email": "samantha@caborealestateservices.com",
    "company": "Cabo Real Estate Services",
    "website": "caborealestateservices.com",
    "city": "Los Cabos",
    "position": "Sales Design And Management",
    "google_rating": "5",
    "score": 60
  },
  {
    "phone": "+528117691122",
    "first_name": "Laura",
    "last_name": "Moreno",
    "email": "lmoreno@gm22.com.mx",
    "company": "GM22 Bienes Raíces",
    "website": "gm22.com.mx",
    "city": "Monterrey",
    "position": "",
    "google_rating": "5",
    "score": 60
  },
  {
    "phone": "+529994866941",
    "first_name": "Wendy",
    "last_name": "Segura",
    "email": "wendy@sendabienesraices.com",
    "company": "Senda Bienes Raíces",
    "website": "sendabienesraices.com",
    "city": "Merida",
    "position": "Partner and Administration Manager",
    "google_rating": "4.9",
    "score": 60
  },
  {
    "phone": "+529999021998",
    "first_name": "Priscila",
    "last_name": "Zozaya",
    "email": "priscila@casamerida.mx",
    "company": "Casa Mérida Real Estate",
    "website": "casamerida.mx",
    "city": "Merida",
    "position": "Realtor",
    "google_rating": "4.8",
    "score": 60
  },
  {
    "phone": "+529994990919",
    "first_name": "Bittor",
    "last_name": "Zulueta",
    "email": "bittor.zulueta@colonialmeridarealestate.com",
    "company": "Colonial Merida Real Estate",
    "website": "colonialmeridarealestate.com",
    "city": "Merida",
    "position": "",
    "google_rating": "4",
    "score": 60
  },
  {
    "phone": "+526241436546",
    "first_name": "Daniel",
    "last_name": "Reyna",
    "email": "danielreyna@remaxsunsetview.com",
    "company": "ReMax Sunset View",
    "website": "remaxsunsetview.com",
    "city": "Los Cabos",
    "position": "",
    "google_rating": null,
    "score": 60
  },
  {
    "phone": "+529841762711",
    "first_name": "Rene",
    "last_name": "Villalobos",
    "email": "rene@hometulum.com",
    "company": "Properties in tulum l HOME TULUM REAL ESTATE",
    "website": "hometulum.com",
    "city": "Tulum",
    "position": "",
    "google_rating": "4.9",
    "score": 60
  },
  {
    "phone": "+529985590044",
    "first_name": "Michelle",
    "last_name": "Romero",
    "email": "mromero@highlinemexico.com",
    "company": "Highline México - Real Estate / Inmobiliaria",
    "website": "highlinemexico.com",
    "city": "Tulum",
    "position": "",
    "google_rating": "4.9",
    "score": 60
  },
  {
    "phone": "+529988859022",
    "first_name": "Leticia",
    "last_name": "Vazquez",
    "email": "leticia.vazquez@century21apolo.com",
    "company": "CENTURY 21 Apolo Cancún",
    "website": "century21apolo.com",
    "city": "Cancun",
    "position": "",
    "google_rating": "5",
    "score": 60
  },
  {
    "phone": "+18056182012",
    "first_name": "Samantha",
    "last_name": "Ross",
    "email": "samantha@oceansideloscabos.com",
    "company": "Oceanside Real Estate Group (Cabo San Lucas)",
    "website": "oceansideloscabos.com",
    "city": "Los Cabos",
    "position": "Real Estate Agent",
    "google_rating": "5",
    "score": 60
  },
  {
    "phone": "+529985001810",
    "first_name": "Lucero",
    "last_name": "Alvarez",
    "email": "lalvarez@mlcancunrealestate.com",
    "company": "M & L CANCUN REAL ESTATE",
    "website": "mlcancunrealestate.com",
    "city": "Cancun",
    "position": "",
    "google_rating": null,
    "score": 60
  },
  {
    "phone": "+529981088504",
    "first_name": "Carlos",
    "last_name": "Ortiz",
    "email": "carlos.ortiz@gruposalo.com",
    "company": "Grupo SALO Inmobiliario",
    "website": "gruposalo.com",
    "city": "Cancun",
    "position": "Chief Executive Officer",
    "google_rating": "5",
    "score": 50
  },
  {
    "phone": "+523222249400",
    "first_name": "Maria",
    "last_name": "Lurdes",
    "email": "maria.lurdes@fpbienesraices.com",
    "company": "FP Bienes Raíces y Soluciones",
    "website": "fpbienesraices.com",
    "city": "Puerto Vallarta",
    "position": "",
    "google_rating": "4.9",
    "score": 30
  },
  {
    "phone": "+523221947575",
    "first_name": "Marijo",
    "last_name": "Castro",
    "email": "marijo@cbsvallarta.com",
    "company": "CBS Vallarta",
    "website": "cbsvallarta.com",
    "city": "Puerto Vallarta",
    "position": "",
    "google_rating": "5",
    "score": 30
  }
];
