#!/usr/bin/env python3
"""Regenerate the AUTOGEN-FUNCTIONS block in SYSTEM.md from live index.js exports."""
import re, glob, datetime, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SYS = os.path.join(ROOT, "SYSTEM.md")
IDX = os.path.join(ROOT, "website/functions/index.js")
FUNC_DIR = os.path.join(ROOT, "website/functions")

with open(IDX) as f:
    src = f.read()
exports = sorted(set(re.findall(r"^exports\.([a-zA-Z_][a-zA-Z0-9_]*)", src, re.M)))
count = len(exports)

# Scan only TOP-LEVEL .js files in website/functions/ — avoid node_modules
sched_pat = re.compile(r"""pubsub\.schedule\(["'][^"']+["']\)""")
scheds = set()
for jsfile in glob.glob(os.path.join(FUNC_DIR, "*.js")):
    try:
        with open(jsfile) as f:
            for m in sched_pat.findall(f.read()):
                scheds.add(m)
    except Exception:
        pass
sched_count = len(scheds)

today = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

# Format as 3 columns, padded
def cols3(items, pad=42):
    n = len(items)
    rows = (n + 2) // 3
    out = []
    for r in range(rows):
        a = items[r] if r < n else ""
        b = items[r + rows] if r + rows < n else ""
        c = items[r + 2 * rows] if r + 2 * rows < n else ""
        out.append(f"{a:<{pad}} {b:<{pad}} {c}")
    return "\n".join(out)

formatted = cols3(exports)

block = f"""<!-- AUTOGEN-FUNCTIONS-START -->
<!-- DO NOT EDIT BY HAND. Run `bash tools/regen_system_inventory.sh` to regenerate. -->

> **Autogenerated from `website/functions/index.js` on {today}.**
> **Live count: {count} exported functions, {sched_count} distinct pubsub cron schedules.**
> Hand-curated descriptions for each function live in subsections §1.1–§1.4 below.
> This block is the source-of-truth for *which functions exist right now*.

<details>
<summary><b>Click to expand the full {count}-function inventory</b></summary>

```
{formatted}
```

</details>

<!-- AUTOGEN-FUNCTIONS-END -->"""

with open(SYS) as f:
    content = f.read()

if "AUTOGEN-FUNCTIONS-START" in content:
    content = re.sub(
        r"<!-- AUTOGEN-FUNCTIONS-START -->.*?<!-- AUTOGEN-FUNCTIONS-END -->",
        block, content, count=1, flags=re.DOTALL)
    print("REPLACED existing block")
else:
    marker = "## 1. Cloud Functions (Firebase, us-central1)\n"
    i = content.find(marker)
    if i < 0:
        print("ERROR: cannot find §1 header", file=sys.stderr); sys.exit(1)
    content = content[: i + len(marker)] + "\n" + block + "\n" + content[i + len(marker):]
    print("INSERTED new block after §1 header")

with open(SYS, "w") as f:
    f.write(content)

print(f"OK  count={count}  schedules={sched_count}  block_lines={block.count(chr(10))+1}")
